#!/usr/bin/env python
"""
Feluda API script.
"""

import argparse
import sys

from feluda.api import run_app


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(description="Run the Feluda API")
    parser.add_argument("--host", type=str, default="0.0.0.0", help="Host to bind to")
    parser.add_argument("--port", type=int, default=8000, help="Port to bind to")
    parser.add_argument("--config", type=str, help="Path to the configuration file")
    
    args = parser.parse_args()
    
    run_app(host=args.host, port=args.port, config_path=args.config)


if __name__ == "__main__":
    main()
