#!/usr/bin/env python
"""
Feluda Dashboard script.
"""

import argparse
import sys

from feluda.dashboard import run_dashboard


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(description="Run the Feluda Dashboard")
    parser.add_argument("--host", type=str, default="0.0.0.0", help="Host to bind to")
    parser.add_argument("--port", type=int, default=8050, help="Port to bind to")
    parser.add_argument("--debug", action="store_true", help="Run in debug mode")
    
    args = parser.parse_args()
    
    run_dashboard(host=args.host, port=args.port, debug=args.debug)


if __name__ == "__main__":
    main()
